third_stream: False
center: False
batch_size: 6
num_workers: 4
ckpt_path: ckpt_twostream_attention_coords/
frame_nb: 5
sampling_rate: 1
encoder_type: 'two_stream_temporal_attention'
pretrained_weights: ckpt_multigpu_reproduce
pretrained_epoch: 16
attention_config:
  attention_layers: ['res2', 'res3']
  warping: False
  use_coords: True
  use_aux_loss: False
