third_stream: False
center: False
batch_size: 6
num_workers: 4
ckpt_path: ckpt_twostream_attention_warping_usewarpf/
frame_nb: 5
sampling_rate: 1
encoder_type: 'two_stream_temporal_attention'
newweights_treated: 0 #0: original setup, 1: new weights higher lr, 2: old weights fixed
attention_config:
  attention_layers: ['res2']
  warping: True
  use_coords: False
  use_aux_loss: False
warp_config:
  residual_warp: True
imgseq: True
