third_stream: False
center: False
batch_size: 6
num_workers: 4
ckpt_path: ckpt_testing/
frame_nb: 5
sampling_rate: 1
encoder_type: 'two_stream_temporal_attention'
attention_config:
  attention_layers: ['res2', 'res3', 'res4', 'res5']
  warping: False
  use_coords: False
  use_aux_loss: False
